### ISSUE TITLE
Segmentation fault for some examples

### ISSUE THREAD

**Issue by ArmanIranfar** [deephealthproject/pyeddl#51]
Hi, 
I have installed pyeddl using `conda install -c dhealth pyeddl-cpu` on an AMD EPYC 32-Core Processor running CentOS Linux 7.  I can successfully run some examples of the example folder of the repository, but for some others it crashes with segmentation fault. For example `mnist_mlp_train_batch.py` fails, while `mnist_conv1D.py` compiles and runs successfully. In particular, the segmentation fault occurs when building the model: 

`(DeepHealth) iranfar@eslsrv13:~/pyeddl/examples/NN/1_MNIST$ python3 mnist_mlp_train_batch.py
Downloading mnist
mnist_trX.bin ✓
mnist_trY.bin ✓
mnist_tsX.bin ✓
mnist_tsY.bin ✓
Generating Random Table
CS with low memory setup
Building model
Segmentation fault
`

I have tried this example with different memory levels (low, mid, full) and in all cases segmentation fault happens too.

**Comment by RParedesPalacios** [comment]
Hi, i think this is due to the compilation flags to speedup. In this case it seems that are not suitable for your processor. Perhaps we cold have different compilations and depending on the machine install the suitable. Not sure if it is possible. Let's see if @simleo or @salvacarrion can add more information.

**Comment by salvacarrion** [comment]
@RParedesPalacios Yes, I think this happens because the HCP flag is enabled when creating the Python binding.

**Comment by RParedesPalacios** [comment]
Yes i figured out, but any solution?

**Comment by salvacarrion** [comment]
I'm talking with Simone for a fix

**Comment by simleo** [comment]
Hi.

Enabling or disabling the HPC flag has nothing to do with the creation of the Python bindings. It's an EDDL compilation flag that may or may not be enabled when building EDDL. Recent EDDL versions have it enabled by default, while older ones have it disabled by default.

The latest conda package currently available is pyeddl 0.9.0 / eddl 0.7.1, and in eddl 0.7.1 the HPC flag is disabled by default (and the conda build setup does not enable it). So this is not due to the HPC flag.

However, the conda package is a binary package and may not be compatible with your CPU, whose architecture I'm not familiar with. So C++ eddl code would likely crash as well, since the pyeddl package is based on the eddl one (you can try running C++ eddl examples to check). You can take a look at https://github.com/deephealthproject/conda_builds to see how the conda package is generated. However, I suggest building from source or using the docker images to get the latest version. See https://deephealthproject.github.io/pyeddl/installation.html for installation instructions and https://github.com/deephealthproject/docker-libs for the docker images.

**Comment by RParedesPalacios** [comment]
In the same way we have this two options:

conda install -c dhealth pyeddl-cpu  # cpu-only version
conda install -c dhealth pyeddl-gpu  # gpu-enabled version

could we have tow more options with HPC disabled?:

conda install -c dhealth pyeddl-cpu-nohpc  # cpu-only version without HPC flag
conda install -c dhealth pyeddl-gpu-nohpc  # gpu-enabled version without HPC flag

**Comment by simleo** [comment]
> In the same way we have this two options:
> 
> conda install -c dhealth pyeddl-cpu # cpu-only version
> conda install -c dhealth pyeddl-gpu # gpu-enabled version
> 
> could we have tow more options with HPC disabled?:
> 
> conda install -c dhealth pyeddl-cpu-nohpc # cpu-only version without HPC flag
> conda install -c dhealth pyeddl-gpu-nohpc # gpu-enabled version without HPC flag

The version with the HPC flag on would not work, since it would be compiled on one machine and run on another one. Same thing as the docker images. With aggressive flags such as `-march=native` the CPU would have to be exactly the same (or maybe a more recent version of the same). It's the kind of flag Gentoo users enable, since they build everything from source. So to get top performance you have to build from source.

**Comment by RParedesPalacios** [comment]
Well, I can not help. I have suggested Simone to generate new Conda packages but it seems is not posible/feasible... not sure. It seems that the solution is to use docker images.

**Comment by simleo** [comment]
> Well, I can not help. I have suggested Simone to generate new Conda packages but it seems is not posible/feasible... not sure. It seems that the solution is to use docker images.

It is possible, Conda packages will hopefully be updated soon. Compiling for all possible architectures, however, is unthinkable, and no single user can have all possible hardware available for development and testing. In cases where someone has a particular architecture, I think the best course is to build from source. Again, if HPC aggressive flags are required, building from source is necessary anyway.

Regarding Docker images: if building from source is not desired or necessary, I think Docker images have a better chance to work on diverse architecture than binary packages.

**Comment by ilveroluca** [comment]
I'm afraid the architecture problem would also persist in Docker.  We just compile the libraries without special architecture instructions.

Maybe we provide instructions to build the conda package from source?  Conda should take care of all dependencies making the process relatively straightforward for the user.

**Comment by simleo** [comment]
> Maybe we provide instructions to build the conda package from source? Conda should take care of all dependencies making the process relatively straightforward for the user.

The https://github.com/deephealthproject/conda_builds repository includes the Conda recipes and a build setup based on simple Makefiles and Dockerfiles. I've just added a section on package building to the readme to further clarify the process.

**Comment by ArmanIranfar** [comment]
I have tested the failing examples on another machine with Intel Xeon Gold 6154 CPU. The same happens. 

Also I have noticed that the crash occurs for particular optimizers; for instance, `eddl.Adadelta` fails while `eddl.rmsprop` works for the same example. I'm not sure this information helps you or not though.

**Comment by RParedesPalacios** [comment]
Adadelta is not yet implemented. Only SGD, Adam and RMSprop.

**Comment by ArmanIranfar** [comment]
> Adadelta is not yet implemented. Only SGD, Adam and RMSprop.

sgd(0.001, 0.9) crashes while sgd(0.01, 0.9).

**Comment by simleo** [comment]
I've updated the conda packages, only pyeddl-cpu (to 0.12.0) and eddl-cpu (to 0.8.3a0) for now. @ArmanIranfar try updating and let me know if there's any difference.

**Comment by ArmanIranfar** [comment]
I tried it in both Intel Xeon and and AMD EPYC machines and  they're all good. No segmentation fault anymore! Thanks!

**Comment by simleo** [comment]
> I tried it in both Intel Xeon and and AMD EPYC machines and they're all good. No segmentation fault anymore! Thanks!

OK. Closing. Thanks to everyone who helped!
